### ISSUE TITLE
I'm confused. by the syntax to employ

### ISSUE THREAD

**Issue by dragutux** [brouznouf/fivem-mysql-async#1]
Hi, so i am trying to use your lib to fix the infamous "there is already an opened datareader..."
here the syntax i use derived from the example : 

require "resources/mysql-async/lib/MySQL"
require "resources/mysql-async/lib/Sync"

function testSQL()
	--local players = {}
	local players = MySQL.Sync.fetchAll('SELECT id, identifier FROM users', '', '')
	
	for k,v in pairs(players) do
		print(v.id)
		print(v.identifier)
	end
end

testSQL()

and here what the server console returns (nulls there, and i can't seem to be able to do -for example- a select * from ..)

![image](https://cloud.githubusercontent.com/assets/5103764/26523778/f10cbdb8-431e-11e7-8b02-6b59fb458dce.png)

**Comment by dragutux** [comment]
note that my prévious test in the console is from a select *

**Comment by joelwurtz** [comment]
I just updated the library can you try with the last version ?

Also you don't need add mysql-async to your `.yml` it was a misunderstanding from my part on how loading was working. (It's not in the installation instructions anymore)

And i just test your code, and i don't have any problems (but i have to remove the id in the query as i don't have it in my table) :

```
require "resources/mysql-async/lib/MySQL"

local players = MySQL.Sync.fetchAll('SELECT identifier FROM users')

print(players)

for k,v in pairs(players) do
    print(v.identifier)
end
```

You should be aware also that MySQL errors (like bad query) are ATM, poorly handled. Errors management, will be done in the next release

**Comment by joelwurtz** [comment]
Ok forget my comment, i'm stupid, find the error, will fix in 2 min

**Comment by joelwurtz** [comment]
Should be good with the last commit

**Comment by dragutux** [comment]
will check

**Comment by dragutux** [comment]
good, it is indeed fixed, but here the problem that happen if i do a "select * from users" here the full code : 
function testSQL()
	local players = MySQL.Sync.fetchAll('SELECT * FROM users', '', '')
	
	for k,v in pairs(players) do
		print(v)
	end
end

testSQL()

the data is stored obviously but i have no idea how to read it, i guess the lib doesn't either ? or maybe i use the wrong request type ? (should not do a fetchAll ??)
here the console results : 
![image](https://cloud.githubusercontent.com/assets/5103764/26524085/6c42201e-4328-11e7-81e3-e21ea2ba3a34.png)

**Comment by joelwurtz** [comment]
It's because v is an object (a LuaTable to be precise), so print(v) does not work as this object does not have a toString method.

In order to get data you can see the schema of your database, like if you have an identifier field you can do print(v.identifier)`

According to https://github.com/neolithos/neolua/blob/master/NeoLua/LuaTable.cs you can also iterate over keys by using v.Keys (not sure if this works)

**Comment by dragutux** [comment]
i did try printing v.identifier with the select * but that did not work :/

**Comment by dragutux** [comment]
what i did try : 
print(tostring(v) & print(tostring(v.identifier))

none of this work...
i can dump my users table but it has not anything specific appart a few fields to store lastpos and what not...

**Comment by dragutux** [comment]
anyway this is non blocking as needed fields can be selected (select * being evil) but for the sake of coding, would be great to know how to convert the result :P

**Comment by dragutux** [comment]
closing this as "non blocking but annoying".
