### ISSUE TITLE
I need help with EACCES error

### ISSUE THREAD

**Issue by Domitresku** [brouznouf/fivem-mysql-async#100]
Yesterday, my server was running normally, but now? This happened

[ERROR] connect EACCES 127.0.0.1:3306

[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM items": connect EACCES 127.0.0.1:3306
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM jobs": connect EACCES 127.0.0.1:3306

SCRIPT ERROR: @es_extended/server/common.lua:23: bad argument #1 to 'for iterator' (table expected, got nil)
> ref (@es_extended/server/common.lua:23)
> setImmediate (@mysql-async/mysql-async.js:14431)

SCRIPT ERROR: @es_extended/server/common.lua:35: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:197)

Help me if you know please, I would be very thankful.

**Comment by SienkoV2** [comment]
Did you have resolve this problem ? :(

**Comment by SienkoV2** [comment]
> Yesterday, my server was running normally, but now? This happened
> 
> [ERROR] connect EACCES 127.0.0.1:3306
> 
> [ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM items": connect EACCES 127.0.0.1:3306
> [ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM jobs": connect EACCES 127.0.0.1:3306
> 
> SCRIPT ERROR: @es_extended/server/common.lua:23: bad argument #1 to 'for iterator' (table expected, got nil)
> 
> > ref (@es_extended/server/common.lua:23)
> > setImmediate (@mysql-async/mysql-async.js:14431)
> 
> SCRIPT ERROR: @es_extended/server/common.lua:35: attempt to get length of a nil value (local 'result')
> 
> > fn (@mysql-async/lib/MySQL.lua:197)
> 
> Help me if you know please, I would be very thankful.

Did you have resolve this problem ? :(

**Comment by GHMatti** [comment]
Configure your firewall correctly.
