### ISSUE TITLE
Deprecated API's

### ISSUE THREAD

**Issue by TheDumpap** [brouznouf/fivem-mysql-async#101]
(node:26456) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:26456) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:26456) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

Latest FXServer Artifacts throws these warnings in console. This is due to a Node update. This issue has been fixed in the latest MySQL module for node - just needs to be implemented here.

**Comment by NotixMLG** [comment]
(node:1454) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:1454) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:1454) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:1454) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:1454) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
(node:1454) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

**Comment by Tinky124** [comment]
(node:5412) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:5412) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:5412) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:5412) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.


Lastest FXServer using also!!

**Comment by ihatetn931** [comment]
Any one find a fix to get rid of the warnings? I attempted it but I do not know much about js

**Comment by mrquentinh** [comment]
Nobody find a way to fix it ? Owner can update script ?

**Comment by chandanroksjsr** [comment]
any fixes for this devs ?

**Comment by Cactusje** [comment]
We need this update

**Comment by dutchplayers** [comment]
> Someone?

` Hello? `

**Comment by mrquentinh** [comment]
Solution is #103 here

**Comment by GHMatti** [comment]
Fixed. You can just download the repository again.
