### ISSUE TITLE
Errors & Spam

### ISSUE THREAD

**Issue by Enric42** [brouznouf/fivem-mysql-async#102]
> Creating script environments for disc-vehiclesales
> SCRIPT ERROR in call ref: TypeError: Cannot read property 'execute' of null
> 
> > global.exports [as callback] (@mysql-async/mysql-async.js:4927)
> > execute (@mysql-async/lib/MySQL.lua:134)
> > handler (@disc-vehiclesales/server/main.lua:11)
> 
> Started resource disc-vehiclesales

and when this server is launched

> [MySQL:5.7.26] [disc-property] [1ms] SELECT * FROM disc_property
> [MySQL:5.7.26] [disc-property] [1ms] SELECT * FROM disc_property_owners where active
> [MySQL:5.7.26] [disc-property] [1ms] SELECT * FROM disc_property
> [MySQL:5.7.26] [disc-property] [1ms] SELECT * FROM disc_property_owners where active
> [MySQL:5.7.26] [disc-property] [1ms] SELECT * FROM disc_property
> [MySQL:5.7.26] [disc-property] [1ms] SELECT * FROM disc_property_owners where active
>

**Comment by stianhje** [comment]
This has nothing to do with mysql-async. Contact the creator of disc-property and disc-vehiclesales
