### ISSUE TITLE
mysql-async Deprecated API

### ISSUE THREAD

**Issue by ArkSeyonet** [brouznouf/fivem-mysql-async#103]
When you are using the latest artifacts for FXServer, if you are using the latest mysql-async you will get deprecation warnings. Using this version with a newer mysqljs has fixed the issue: https://github.com/brouznouf/fivem-mysql-async/releases/tag/3.1.1

**Comment by mrquentinh** [comment]
What action do you need to have the newer mysqljs ?

**Comment by ArkSeyonet** [comment]
Download the release that I linked and use it.

**Comment by mrquentinh** [comment]
Ok I try it thank you !

**Comment by SKYZ3X** [comment]
Thanks you bro

**Comment by KuroSenseii** [comment]
same here and i have lasted release 3.2.0

**Comment by GHMatti** [comment]
Fixed.
