### ISSUE TITLE
[HELP] - DeprecationWarning error

### ISSUE THREAD

**Issue by ozanozkanozanozkan** [brouznouf/fivem-mysql-async#104]
**Hello, I get an error like this when I started CMD. It gives a high ping. How can I solve it?**
![unknown](https://user-images.githubusercontent.com/58013525/69288738-78423580-0c0b-11ea-80df-93a62356f58b.png)

**Comment by mrquentinh** [comment]
Solution is #103 here

**Comment by GHMatti** [comment]
Fixed it. No update as of yet, since I want to update vuetify.
