### ISSUE TITLE
Trying to raise timout threshold, not working

### ISSUE THREAD

**Issue by schwim0341** [brouznouf/fivem-mysql-async#105]
Hi there,

I'm getting inactivity timeouts on server start so tried to raise the inactivity timeout threshold but it doesn't seem to be working.  I'm modifying the following in mysql-async.js:

```
  if (opts.timeout === undefined) {
    // default timeout of 30 seconds
    opts.timeout = 90000;
  }
```

But although the startup of the server isn't taking anywhere near this amount of time, I'm still receiving a wave of inactivity timeouts **during startup only**, I think because of the large number of resources I'm loading(mostly vehicles).  Once the server is done with the startup processes, I receive no errors at all.  Players load in just fine, data is pulled and stored without issue.

Pastebin of entire startup log: https://pastebin.com/pzvUm3JJ

> [MySQL] [Slow Query Warning] [esx_muscleandclassicshop] [17205ms] SELECT * FROM muscleandclassic_categories
> [ERROR] [MySQL] [esx_muscleandclassicshop] An error happens on MySQL for query "SELECT * FROM muscleandclassic_categories": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_eden_garage] [17188ms] UPDATE owned_vehicles SET state=true WHERE state=false
> [ERROR] [MySQL] [esx_eden_garage] An error happens on MySQL for query "UPDATE owned_vehicles SET state=true WHERE state=false": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_vehicleshop] [17187ms] SELECT * FROM vehicle_categories
> [ERROR] [MySQL] [esx_vehicleshop] An error happens on MySQL for query "SELECT * FROM vehicle_categories": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_aircraftshop] [17186ms] SELECT * FROM aircraft_categories
> [ERROR] [MySQL] [esx_aircraftshop] An error happens on MySQL for query "SELECT * FROM aircraft_categories": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_trailershop] [17184ms] SELECT * FROM trailers_categories
> [ERROR] [MySQL] [esx_trailershop] An error happens on MySQL for query "SELECT * FROM trailers_categories": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_shops] [17183ms] SELECT * FROM items
> [ERROR] [MySQL] [esx_shops] An error happens on MySQL for query "SELECT * FROM items": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_datastore] [17181ms] SELECT * FROM datastore
> [ERROR] [MySQL] [esx_datastore] An error happens on MySQL for query "SELECT * FROM datastore": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_addoninventory] [17180ms] SELECT * FROM items
> [ERROR] [MySQL] [esx_addoninventory] An error happens on MySQL for query "SELECT * FROM items": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_supercarshop] [17179ms] SELECT * FROM supercar_categories
> [ERROR] [MySQL] [esx_supercarshop] An error happens on MySQL for query "SELECT * FROM supercar_categories": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_motorcycleshop] [17153ms] SELECT * FROM motorcycle_categories
> [ERROR] [MySQL] [esx_motorcycleshop] An error happens on MySQL for query "SELECT * FROM motorcycle_categories": Handshake inactivity timeout
> [MySQL] [Slow Query Warning] [esx_trunk] [17217ms] DELETE FROM `trunk_inventory` WHERE `owned` = 0
> [MySQL] [Slow Query Warning] [esx_trunk] [17243ms] SELECT * FROM trunk_inventory
> [MySQL] [Slow Query Warning] [esx_truckandsuvshop] [17243ms] SELECT * FROM truckandsuv_categories
> [MySQL] [Slow Query Warning] [esx_pharmacy] [17248ms] SELECT * FROM items
> [MySQL] [Slow Query Warning] [esx_commercialshop] [17247ms] SELECT * FROM commercial_categories
> [MySQL] [Slow Query Warning] [esx_rallyjob] [17246ms] SELECT * FROM rally_times WHERE 1
> [MySQL] [Slow Query Warning] [esx_boatshop] [17244ms] SELECT * FROM boat_categories
> [MySQL] [Slow Query Warning] [esx_addonaccount] [17243ms] SELECT * FROM addon_account
> [MySQL] [Slow Query Warning] [esx_eden_boatgarage] [17241ms] UPDATE owned_boats SET state=true WHERE state=false
> [MySQL] [Slow Query Warning] [esx_eden_aircraftgarage] [17382ms] UPDATE owned_aircrafts SET state=true WHERE state=false
> [MySQL] [Slow Query Warning] [esx_bennysautoshop] [17394ms] SELECT * FROM bennysauto_categories
> [MySQL] [Slow Query Warning] [gcphone] [17392ms] DELETE FROM phone_messages WHERE (DATEDIFF(CURRENT_DATE,time) > 10)
> [MySQL] [Slow Query Warning] [es_extended] [17391ms] SELECT * FROM items
> [MySQL] [Slow Query Warning] [es_extended] [17392ms] SELECT * FROM jobs
> [MySQL] [Slow Query Warning] [esx_property] [17392ms] SELECT * FROM properties
> [MySQL] [Slow Query Warning] [esx_society] [17389ms] SELECT * FROM jobs

Any idea on what I can do to get the resource to be a bit more patient?

**Comment by GHMatti** [comment]
Should be fixed.

**Comment by TLBRP** [comment]
wtf do you mean 'should be fixed'??? i see you everywhere @GHMatti you're a bit of a cunt and never actually provide answers that help. you constantly belittle people and leave threads useless to go back in time and look at when you have the same issues!!

**Comment by 72-Sniper** [comment]
lol thats fuvked
