### ISSUE TITLE
Please help... script error fivem

### ISSUE THREAD

**Issue by XGameRyt** [brouznouf/fivem-mysql-async#107]
SCRIPT ERROR in call ref: TypeError: Cannot read property 'execute' of null

> callback (@mysql-async/mysql-async.js:5112)
> fetchAll (@mysql-async/lib/MySQL.lua:147)
> ? (@es_extended/server/main.lua:48)
> fn (@async/async.lua:21)

**Comment by GHMatti** [comment]
No reproduction steps.
