### ISSUE TITLE
LAST_INSERT_ID Problem on FiveM Server vRP Framework

### ISSUE THREAD

**Issue by NozyGG** [brouznouf/fivem-mysql-async#112]
Hellp, I have a really big problem with mysql-async for FiveM with vRP framework, when someone connects to the server the LAST_INSERT_ID doesn't work it gives nil value and it says this error

[ERROR] [MySQL] [vrp] An error happens on MySQL for query "INSERT INTO vrp_user_ids(identifier,user_id) VALUES('steam:11000010856762b',@user_id)": ER_BAD_NULL_ERROR: Column 'user_id' cannot be null

how can I fix LAST_INSERT_ID ? please help !

**Comment by schwim0341** [comment]
You're not providing the user_id to the mysql statement.

**Comment by NozyGG** [comment]
Can you please show me how to provide the user_id to the mysql statement? Please i have searched for ages to fix it
