### ISSUE TITLE
How to get data out of the callback?

### ISSUE THREAD

**Issue by Ex0r** [brouznouf/fivem-mysql-async#116]
When trying to use a MySql.Async.fetchAll(), inside of the callback, I cannot seem to get variables to be set and accessible outside of the callback. 

I have access to a variable outside of the callback, but once I change it in the callback, it's not updated outside of it. Is there a way to pass the variable in so that I can manipulate it and get it back out?

**Comment by TimBunk** [comment]
I am having the same issue at the moment and I also can't trigger client events within the callback.

**Comment by djmetla** [comment]
Any solution for this? Currently this lib is unusable

**Comment by Rubylium** [comment]
```
MySQL.Async.fetchAll('SELECT * FROM player', {}, function(players)
    print(players[1].name)
end)
```

**Comment by Ex0r** [comment]
This doesn't help with storing the value outside of the callback, or
updating a variable while inside the callback.

**Comment by Ex0r** [comment]
An example is this:

`if checkPlayerExists(identifier) then
  do this stuff
end
function checkPlayerExists(identifier)
  MySQL.Async.fetchAll('SELECT * FROM `users` WHERE `identifier` = @identifier',
    {
      ['@identifier'] = identifier,   
    }, function(result)
      if #result < 1 then
         return false
      end
  end)
end
`

**Comment by CaioCartaxo** [comment]
I have the same problem here, even in the buggy IVMP I can work with the returned value and not here ...
