### ISSUE TITLE
Transaction is broken

### ISSUE THREAD

**Issue by Scotty1944** [brouznouf/fivem-mysql-async#118]
I tried to use a new transaction in 3.2.0 yea it worked, but!
sometimes it broke MySQL connection, you can't fetch, execute or transaction (nothing happen)
I put some print function at mysql-async\lib\MySQL.lua

![image](https://user-images.githubusercontent.com/50376916/75601857-1b032d80-5af2-11ea-94cd-37f80f7c5da7.png)

and saw it called that function but nothing happen
when I remove transaction everything is working fine without any problem

So I think a transaction is broken anyone has the same problem?

**Comment by Neddings** [comment]
@Scotty1944 Apply the details from pull request #98 to your version and the problem should be solved.

**Comment by GHMatti** [comment]
No. Any repro?
