### ISSUE TITLE
Question :

### ISSUE THREAD

**Issue by Slyker** [brouznouf/fivem-mysql-async#119]
Hi,

I saw a vSql version on fivem forum, i tried to mix vSql and this resource, it's working great, do you think my idea was good ? vSql creator said that his resource is faster than this one, that's why i tried this mix

Waiting for your returns

**Comment by GHMatti** [comment]
The limiting factor for either MySQL implementation is not speed but bandwidth, and that is throughly gated by the fxserver, so it does not matter which one is "faster", as long as you are able to fill the server export bandwidth without the implementation dying, you are fast enough.
