### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by zoomlordir** [brouznouf/fivem-mysql-async#120]
hi I'm using the latest version of mysql-async
and i just have this problem on my VPS , on my local pc it's fine and no errors happend
i try to unblocking the ports and nothing happend
i can connect to mysql very quick and esay and mysql is fine
what can i do?
Errors :
[ERROR] [MySQL] [esx_addoninventory] An error happens on MySQL for query "SELECT * FROM items": connect ETIMEDOUT
[ERROR] [MySQL] [esx_addonaccount] An error happens on MySQL for query "SELECT * FROM addon_account": connect ETIMEDOUT
[ERROR] [MySQL] [esx_datastore] An error happens on MySQL for query "SELECT * FROM datastore": connect ETIMEDOUT
[ERROR] [MySQL] [esx_trunk] An error happens on MySQL for query "SELECT * FROM trunk_inventory": connect ETIMEDOUT
[ERROR] [MySQL] [esx_trunk] An error happens on MySQL for query "DELETE FROM `trunk_inventory` WHERE `owned` = 0": connect ETIMEDOUT
[ERROR] [MySQL] [esx_quincaillerie] An error happens on MySQL for query "SELECT * FROM items": connect ETIMEDOUT
[ERROR] [MySQL] [esx_society] An error happens on MySQL for query "SELECT * FROM jobs": connect ETIMEDOUT
[ERROR] [MySQL] [esx_eden_garage] An error happens on MySQL for query "UPDATE owned_vehicles SET state=true WHERE state=false": connect ETIMEDOUT
[ERROR] [MySQL] [esx_pharmacy] An error happens on MySQL for query "SELECT * FROM items": connect ETIMEDOUT

**Comment by Darcheur** [comment]
did you fix that?

**Comment by zoomlordir** [comment]
> did you fix that?

nope my sql works fine and i dont know why this error showing up

**Comment by Darcheur** [comment]
> > did you fix that?
> 
> nope my sql works fine and i dont know why this error showing up

I found a solution you need to update the main resources
like esx_billing / esx_datastore / esx_addonaccount etc

**Comment by zoomlordir** [comment]
> > > did you fix that?
> > 
> > 
> > nope my sql works fine and i dont know why this error showing up
> 
> I found a solution you need to update the main resources
> like esx_billing / esx_datastore / esx_addonaccount etc

I will try it

**Comment by zoomlordir** [comment]
**It doesn't work for me**
Now other errors have disappeared and only this error is displayed
**[ERROR] connect ETIMEDOUT**

**Comment by zoomlordir** [comment]
finally fixed 🦺 🧑‍🦯

**Comment by Vigilioon** [comment]
Hi @zoomlordir can you tell me how you fix that ?

**Comment by bandidom9** [comment]
if you fix something please say how so others with the issue know what to try.

**Comment by zoomlordir** [comment]
The reason for this error is the version of resources
resources need **sync** by **SQL** must have a version and this version must be same in **mysql-async** and resource
**so you need to use older version of mysql-async like version 2.0.0 or update your resources**
@bandidom9
@Vigilioon

**Comment by Amado1000** [comment]
For me
I've updated the basic resources.
And the second time I got the error, I updated mysql-async.

**Comment by GHMatti** [comment]
Which server are you running?

**Comment by pedrinhoskdaniel** [comment]
I keep getting esx_eden_garage error, can anyone help me?

**Comment by Domitresku** [comment]
It's because when your server resources load slowly. When your server starts, close it and immidiately start another one, it helps me a lot

**Comment by Chip-W** [comment]
I have a very large MLO that loads slow.  I moved it to the top of the list since it's not dependent on anything else so that it loads before any mysql stuff and seemed to fix my issue.
