### ISSUE TITLE
Problem Connect etimedout

### ISSUE THREAD

**Issue by Darcheur** [brouznouf/fivem-mysql-async#121]
[ERROR] connect ETIMEDOUT
[ERROR] [MySQL] [esx_jb_advanced_truck_inventory] An error happens on MySQL for query "DELETE FROM `truck_inventory` WHERE `count` = 0": connect ETIMEDOUT
[ERROR] [MySQL] [esx_datastore] An error happens on MySQL for query "SELECT * FROM datastore": connect ETIMEDOUT
[ERROR] [MySQL] [esx_weaponshop] An error happens on MySQL for query "SELECT * FROM weashops": connect ETIMEDOUT
[ERROR] [MySQL] [esx_society] An error happens on MySQL for query "SELECT * FROM jobs": connect ETIMEDOUT

I need help very quick pls

**Comment by Darcheur** [comment]
I found

**Comment by Vigilioon** [comment]
Hi @Darcheur  can you tell me how you fix that ?
