### ISSUE TITLE
cad computer comes out as???????????????

### ISSUE THREAD

**Issue by ShaggyRogersTBS** [brouznouf/fivem-mysql-async#122]
So i'm running a document script and a polic mdt scrtipt an the problem is that when someone types something in bulgarian/cirillyc the db saves it as ????????? instead for example: нещо си там. can yuou tell me how am i supposed to change the charset of the scriptl, or the whole sql thing

**Comment by GHMatti** [comment]
Use the string, change the charset to something that is not UTF8_GENERAL_CI
