### ISSUE TITLE
Empty mysql-connection-string detected

### ISSUE THREAD

**Issue by Nexobeta28** [brouznouf/fivem-mysql-async#128]
Im seting up a localhost server with XAMPP for making resources. Im using ESX Extended, when I launch the server Im getting this:
![image](https://user-images.githubusercontent.com/30263316/82335828-23c91880-99ea-11ea-98d5-4101f7b4ff18.png)

This is my server.cfg:
![image](https://user-images.githubusercontent.com/30263316/82336010-56731100-99ea-11ea-86d2-c767bf74da98.png)

I tried with another account too, not root, and another convar style, but im getting the same.

Let me know if I need to add more information to solve the problem, thanks.

**Comment by Nexobeta28** [comment]
Solved! Just add the convar before the start mysql-async, like this:

![image](https://user-images.githubusercontent.com/30263316/82343455-2a0fc280-99f3-11ea-966d-6c9f9bbceaaa.png)

**Comment by GHMatti** [comment]
by the way you can omit server=localhost and uid if the user is root. it defaults to that.
