### ISSUE TITLE
Fails to save user data on localhost

### ISSUE THREAD

**Issue by daZepelin** [brouznouf/fivem-mysql-async#133]
If in server there are at least like 4-5 people I sometimes start getting the error below. Server is hosted on vps and uses local host database. If I save each user manually it does save them just fine. Don't know if it's caused by SQL or esx
`[WARNING] Failed to automatically save player data! This may be caused by an internal error on the MySQL server.`

**Comment by GHMatti** [comment]
There is a nice issue template. I have no idea how to get this result, so I cannot help.
