### ISSUE TITLE
Failed to load script mysql-async-client.js

### ISSUE THREAD

**Issue by deenz-cfx** [brouznouf/fivem-mysql-async#134]
Using lastest es_extended or Extendedmode, in both ways i still getting this error.

![Screenshot_1](https://user-images.githubusercontent.com/66654706/84097245-41473c00-aa04-11ea-9ebc-99e2790261c3.png)

**Comment by GHMatti** [comment]
This is not an issue with esx, but a recent FiveM change. They removed the window instance, which I used to avoid linting issues.

Fix will be soon.

**Comment by GHMatti** [comment]
Fixed.

**Comment by new2020** [comment]
> Fixed.

now i have the same problem, what can i do?
