### ISSUE TITLE
How to show only warnings on console?

### ISSUE THREAD

**Issue by deenz-cfx** [brouznouf/fivem-mysql-async#136]
After the last update everything is being showed on the console, is there any way to disable it? like it used to be? just warnings? every change on the database shows up, and it makes it hard to read the console, ty in advance.
![Screenshot_2](https://user-images.githubusercontent.com/66654706/85019687-7de70600-b16f-11ea-9c3f-ac33beb21fb9.png)

**Comment by GHMatti** [comment]
`set mysql_debug "None"`

or

`set mysql_debug "File"`

before `start mysql-async`.

I think it defaults to FileAndConsole if a faulty input is made, will fix that whenever I feel like it.

**Comment by deenz-cfx** [comment]
> `set mysql_debug "None"`
> 
> or
> 
> `set mysql_debug "File"`
> 
> before `start mysql-async`.
> 
> I think it defaults to FileAndConsole if a faulty input is made instead of None, will fix that whenever I feel like it.

Thank you so much man!

**Comment by gabrielcalderon** [comment]
@GHMatti I'm still getting all the debug logs on the console even after setting. Using latest mysql-async and fxserver 2625

```
set mysql_debug "None"
start mysql-async
```

**Comment by GHMatti** [comment]
Use "File", i got some reports saying None does not work. I currently do not have time to look into that.

**Comment by wolgix** [comment]
doesnt work, still spam console
