### ISSUE TITLE
Ridiculous errors in the console

### ISSUE THREAD

**Issue by yagizher** [brouznouf/fivem-mysql-async#137]
Hi, i've seen people experiencing this, too much.
![image](https://user-images.githubusercontent.com/52376710/85135332-98d87980-b246-11ea-94ff-24b1a0b574a6.png)
And it seems that mysql-async is what causes this.

**Comment by GHMatti** [comment]
Old resource. No proper report.

**Comment by yagizher** [comment]
Its up-to-date, edited the issue.

**Comment by GHMatti** [comment]
Yeah, C# errors while the up to date resource runs on javascript. easy to see.

**Comment by nokasahar** [comment]
![image](https://user-images.githubusercontent.com/34238392/85196736-e9061900-b2e4-11ea-8adb-c5c22406763c.png)
i need help .
