### ISSUE TITLE
last_insert_id is missing from the API

### ISSUE THREAD

**Issue by JamieH** [brouznouf/fivem-mysql-async#14]
As far as I can tell last_insert_id is missing from the MySQL API you expose, please could it be added? I'm using the FXServer version. If it's already usable could I get an example please? Thanks ❤

**Comment by JamieH** [comment]
I managed to get it working using `INSERT INTO vrp_users(whitelisted,banned) VALUES(false,false); SELECT LAST_INSERT_ID();` with `fetchScalar`

**Comment by joelwurtz** [comment]
No way ATM, will provide an option in the future

**Comment by joelwurtz** [comment]
Added in beta 3

**Comment by NozyGG** [comment]
Can I please get help ? I have a FiveM server and I'm using vrp framework and I have the same problem with LAST_INSERT_ID, how can I fix that ? please I need help
