### ISSUE TITLE
Warning Select from Items 1240ms / Warning Select from Jobs 1241ms 

### ISSUE THREAD

**Issue by fabixx021** [brouznouf/fivem-mysql-async#140]
![unknown](https://user-images.githubusercontent.com/53187758/85934276-2f5d0880-b8e1-11ea-8a1c-d07ef9870cdb.png)

I have these warnings in the console. I inquired everywhere but found nothing. Can you help me ?

Many thanks

**Comment by GHMatti** [comment]
This is for bugs only, not for help requests.

This has nothing to do with mysql-async, the issue lies with es_extended.
