### ISSUE TITLE
choose folder of logs

### ISSUE THREAD

**Issue by wolgix** [brouznouf/fivem-mysql-async#141]
Hello, i would like to choose path, where will my logs save, when using set mysql_debug "File"

You dont wanna see my main server folder after 1 month of running :D

log everywhere :D

**Comment by GHMatti** [comment]
Added the option to set a name for the logging file in https://github.com/GHMatti/ghmattimysql/commit/81643d5e94efb840606472b1094bd2b3ccb19688
