### ISSUE TITLE
Error resuming coroutine (MySQL)

### ISSUE THREAD

**Issue by Lokegithub** [brouznouf/fivem-mysql-async#142]
I get this error all the time : 
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:164: in field 'fetchAll'
        server/main.lua:19: in function <server/main.lua:15>

Someone knows how to fix this?

**Comment by GHMatti** [comment]
See readme. No support in issues.
