### ISSUE TITLE
Small typo in the documentation for MySQL.Async.store 

### ISSUE THREAD

**Issue by PhaserArray** [brouznouf/fivem-mysql-async#143]
I noticed a typo in one of the examples in the documentation . The code example for [store](https://brouznouf.github.io/fivem-mysql-async/#store) defines a variable called `insertUserLog`, but in the callback for `MySQL.Async.store` it assigns to `insertUser`.

It's a tiny and unimportant issue, but it confused me for a few seconds, so I figured I'd bring it up.

![example](https://user-images.githubusercontent.com/10397412/88106768-ac149700-cbae-11ea-8b22-979e26973ce0.png)

**Comment by GHMatti** [comment]
Thank you.
