### ISSUE TITLE
"WHERE @column = @data" isn't possible

### ISSUE THREAD

**Issue by Puntherline** [brouznouf/fivem-mysql-async#145]
**Is your feature request related to a problem? Please describe.**
I want to trigger a function that gets data from the same table but not the same column every time. Code snippet further down.
<br><br>

**Describe the solution you'd like**
I want to be able to replace not only the data to look for in the query, but also the column name.
<br><br>

**Describe alternatives you've considered**
Stacking "if" statements which creates mess.
<br><br>

**Additional context**
Here's my function that get's triggered with a column name and data.
```lua
function myFunction(column, data)
    MySQL.Async.fetchAll("SELECT specificColumn FROM table WHERE @column = @data", {
        ["@column"] = column,
        ["@data"] = data
    }, function(result)
        print(json.encode(result))
    end)
end
```

My uneducated guess is that it's adding quotation marks for the data as it should, same with the column though which is why it fails. I can just stack "if" statements like this, but it's not pretty:
```lua
function myFunction(column, data)
    if column == "column2" then
        MySQL.Async.fetchAll("SELECT column1 FROM table WHERE column2 = @data", {
            ["@data"] = data
        }, function(result)
            print(json.encode(result))
        end)
    elseif column == "column3" then
        MySQL.Async.fetchAll("SELECT column1 FROM table WHERE column3 = @data", {
            ["@data"] = data
        }, function(result)
            print(json.encode(result))
        end)
    --[[...etc...]]
    end
end
```

As to why I want to do this, it's pretty simple. I'm creating a resource that will log identifiers, update them once/if they change, and if too many change you won't be able to log on, further down the road I'll also add ban functionalities and maybe some other stuff, I don't know yet.

Also, sorry if the title is very confusing, I genuinely tried my best.

**Comment by ghost** [comment]
Use the js syntax.
```lua
MySQL.Async.fetchAll("SELECT column1 FROM table WHERE ?", {{ [column] = data }})
```
