### ISSUE TITLE
Connection Timedout

### ISSUE THREAD

**Issue by BManZ07** [brouznouf/fivem-mysql-async#148]
**Describe the bug**
When starting the server all scripts start, but at the bottom the console comes back with [mysql-async] [ERROR] connect ETIMEDOUT
**To Reproduce**
Unsure what directly causes, but happens on every server startup.
**Expected behavior**
Connection successful.
**Screenshots / Logs**
https://gyazo.com/e603919839e2c6334f48c3b076f7ff6a

**Software:**
 - OS: Windows Server 2019
 - Version of the resource: 3.2.2
 - Database Version MariaDB 10.4.14

**Comment by Tinky124** [comment]
Will this be fixed?

**Comment by StayAlone01** [comment]
use like this instead, it some how works
`set mysql_connection_string "mysql://username:password@localhost/database?debug=false&charset=utf8mb4"`
