### ISSUE TITLE
Support for multiple database connections

### ISSUE THREAD

**Issue by ChaosMTA** [brouznouf/fivem-mysql-async#15]
Title explains it. We'd like to use a central auth database and then use another database for the rest so there should be the ability to add multiple configurations.

**Comment by joelwurtz** [comment]
THis induce a lot of code to add and many thing to take care (like passing a connection reference to your mysql functions, add safety check in case of connection not being properly closed etc ...)

You can maybe trick  this by having 2 resources with my library, but i don't want to add this functionnality here as i will have too little time to maintain it (and then this library will be in a poor state).

However if you want to fork this lib and do this go ahead and ping me if you need any help.
