### ISSUE TITLE
Packets out of order. Got: 1 Expected: 0

### ISSUE THREAD

**Issue by Virrefirre** [brouznouf/fivem-mysql-async#150]
**Describe the bug**
I get an error: cfx> [mysql-async] [ERROR] Packets out of order. Got: 1 Expected: 0

**To Reproduce**
Every script that uses MySQL.
esx_society, esx_drp_garage, esx_addonaccount, esx_shops ETC

**Expected behavior**
??

**Screenshots / Logs**
[MySQL] [WARNING] [esx_society] [292ms] SELECT * FROM jobs : []
[MySQL] [ERROR] [esx_society] An error happens for query "SELECT * FROM jobs : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [WARNING] [esx_boat] [282ms] UPDATE owned_vehicles SET `stored` = true WHERE `stored` = false AND type = ? : ["boat"]
[MySQL] [ERROR] [esx_boat] An error happens for query "UPDATE owned_vehicles SET `stored` = true WHERE `stored` = false AND type = ? : ["boat"]": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [esx_shops] An error happens for query "SELECT * FROM shops LEFT JOIN items ON items.name = shops.item : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [WARNING] [esx_datastore] [276ms] SELECT * FROM datastore : []
[MySQL] [ERROR] [esx_datastore] An error happens for query "SELECT * FROM datastore : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [es_extended] An error happens for query "SELECT * FROM items : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [es_extended] An error happens for query "SELECT * FROM jobs : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [esx_joblisting] An error happens for query "SELECT name, label FROM jobs WHERE whitelisted = ? : [false]": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [esx_addoninventory] An error happens for query "SELECT * FROM items : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [WARNING] [esx_addonaccount] [282ms] SELECT * FROM addon_account : []
[MySQL] [ERROR] [esx_addonaccount] An error happens for query "SELECT * FROM addon_account : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [esx_vehicleshop] An error happens for query "SELECT * FROM vehicle_categories : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [esx_vehiclelock] An error happens for query "SELECT owner, plate FROM owned_vehicles : []": Packets out of order. Got: 1 Expected: 0
[MySQL] [ERROR] [esx_vehiclelock] An error happens for query "SELECT owner, plate FROM rented_vehicles : []": Packets out of order. Got: 1 Expected: 0
SCRIPT ERROR: @esx_society/server/main.lua:18: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:226)
SCRIPT ERROR: @esx_shops/server/main.lua:8: attempt to get length of a nil value (local 'shopResult')
> ref (@esx_shops/server/main.lua:8)
> (@mysql-async/mysql-async.js:15543)
SCRIPT ERROR: @esx_addoninventory/server/main.lua:10: attempt to get length of a nil value (local 'items')
> fn (@mysql-async/lib/MySQL.lua:226)
[MySQL] [ERROR] [esx_vehicleshop] An error happens for query "SELECT * FROM vehicles : []": Packets out of order. Got: 1 Expected: 0
SCRIPT ERROR: @esx_addonaccount/server/main.lua:9: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:226)
SCRIPT ERROR: @esx_datastore/server/main.lua:9: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:226)
SCRIPT ERROR: @es_extended/server/common.lua:35: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:226)
SCRIPT ERROR: @esx_vehicleshop/server/main.lua:32: bad argument #1 to 'for iterator' (table expected, got nil)
> ref (@esx_vehicleshop/server/main.lua:32)
> (@mysql-async/mysql-async.js:15543)
[MySQL] [ERROR] [esx_property] An error happens for query "SELECT * FROM properties : []": Packets out of order. Got: 1 Expected: 0
SCRIPT ERROR: @esx_property/server/main.lua:69: attempt to get length of a nil value (local 'properties')
> ref (@esx_property/server/main.lua:69)
> (@mysql-async/mysql-async.js:15543)

**Software:**
 - OS: Windows 10
 - Version of the resource: 3.3.2
 - Database Version: 10.4.13-MariaDB-1:10.4.13+maria~bionic-log - mariadb.org binary distribution

**Comment by nusikales** [comment]
Having the same issue

**Comment by Ezharjan** [comment]
Me too...

**Comment by noahtitu** [comment]
me too
