### ISSUE TITLE
TIMESTAMP / DATETIME

### ISSUE THREAD

**Issue by Identity-labs** [brouznouf/fivem-mysql-async#16]
Les champs de type date semble poser problème

Error invoking callback for event onMySqlQueryFetchAll: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to convert MySQL date/time to System.DateTime.

**Comment by joelwurtz** [comment]
Try to add `ConvertZeroDateTime=true` in the connection string, i think this come from bad value for date time field (like 0000-00-01)

**Comment by joelwurtz** [comment]
Close this as a won't fix, the option should resolve this, reopen it if not (but i don't have any error with timestamp)
