### ISSUE TITLE
FX Server, Impossible to execute any request

### ISSUE THREAD

**Issue by qlaffont** [brouznouf/fivem-mysql-async#17]
Hi,
I have this error : 
`
Exception loading assembly I18N: System.IO.FileNotFoundException: Unable to find the specified file.
`

How I can solve this ?
Regards
Quentin

**Comment by joelwurtz** [comment]
I do not use any I18N assembly, seems strange, sure it's coming from this library ?

**Comment by anarchyrising** [comment]
I'm pretty sure that I18N is a Mono error caused by the FXServer.  FiveM noted that these types of errors were harmless and may happen.  I have this error too and MySql-Async works fine.

**Comment by joelwurtz** [comment]
That"s what i have seen also, closing this then
