### ISSUE TITLE
I keep getting warnings on restarts

### ISSUE THREAD

**Issue by Horchata101** [brouznouf/fivem-mysql-async#173]
**Describe the bug**
I keep getting warnings whenever i start the server 

**Expected behavior**
Every restart

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/83477654/121455418-49a8be80-c959-11eb-8b5e-e8bc915376cf.png)

**Software:**
 - OS: Windows 10
 - Version of the resource: 3.3.2
 - Database Version: HeidiSql 11.3 (latest version)

**Additional context**
I tested everything on my test server before putting into my VPS and it worked perfectly fine

**Comment by iSentrie** [comment]
Your VPS is shit obviously.

**Comment by Horchata101** [comment]
if you are here to not help me don't comment

> Your VPS is shit obviously.
