### ISSUE TITLE
essentialmode 2 plz fix

### ISSUE THREAD

**Issue by malgorzata22** [brouznouf/fivem-mysql-async#18]
after we are moved fxsystem , i can see you have remowed asembly file so essentailmode 2 not wil ork :( will you plz fix again so we can use essentialmode 2 ,

cause else everyone locked too couchdb :(

**Comment by FrBillyD** [comment]
Hello. You need to adapt your code... We have converted essential 2 to this library on fx and it work fine.

Let's go work hard dude 😉

**Comment by joelwurtz** [comment]
2.0 version will not support essentialmode anymore; version 1.0 is here as a bc layer and have, IMO, a great way to rewrite your code with the new API over time.

The more code there is, the more bug the code will have. Having a light code base is better for a majority of people.
