### ISSUE TITLE
Ok, i didn't see the update and i'm now in panic mode...

### ISSUE THREAD

**Issue by dragutux** [brouznouf/fivem-mysql-async#2]
so i upgraded the ressource, filled a config.lua in lib, changed example.lua to this
```
require "resources/mysql-async/lib/MySQL"
require "resources/mysql-async/lib/EssentialModeApi"

function testSQL()
	local players = MySQL.Sync.fetchAll('SELECT identifier FROM users')
	
	for k,v in pairs(players) do
		print(v.identifier)
	end
end
```

and i now have 0 printing to the console :S, if i keep the old init.lua, it crash... 

here my several attempts to get a result....... (the settings are proper btw...)
![image](https://cloud.githubusercontent.com/assets/5103764/26524317/6d4e42ce-432f-11e7-9de9-8b911a3d1b50.png)

**Comment by dragutux** [comment]
By the way if you wish to discuss/live test this with me here is my discord id : @LoursGeek#5895

**Comment by joelwurtz** [comment]
You are missing the call to testSQL no ?

**Comment by dragutux** [comment]
forgot to put it there in code but not it is there :(

**Comment by dragutux** [comment]
stupid me.. apparently yes this is the case...
closing this ^^ and on my way to fix plugins. (altough, some use select * and will be hurt...., i really think you should aim at replacing essentials, lots of people love you already even if you don't know :D)

**Comment by dragutux** [comment]
so, closed, reason : i'm stupid & i rush things.
