### ISSUE TITLE
ntdll load issue on Linux

### ISSUE THREAD

**Issue by Ben080808** [brouznouf/fivem-mysql-async#22]
Hello,
Im running Ubuntu 16.04 LTS
Kernel: Linux vps440251 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux.

I installed fivem-mysql-async, but the Server cant load because it cant find the ntdll

Server Log with Mono Log Level set to Debug: https://pastebin.com/wYUz0SJk

It fails to find or load the ntdll and then fails with

`[ERROR] [] An critical error happens on MySQL for query "SELECT @parameters {@parameters=string}": ntdll.dll   at (wrapper managed-to-native) Interop+NtDll:RtlGetVersion (Interop/NtDll/RTL_OSVERSIONINFOEX&)`

**Comment by GHMatti** [comment]
Try the node version.
