### ISSUE TITLE
crash under windows ?

### ISSUE THREAD

**Issue by bozoweed** [brouznouf/fivem-mysql-async#24]
hi i used you'r mysql async plugin it's awesome but sometime and it's total random, mysql async get crash under windows and linux ( linux is not stable i know ) but befor use that my server was full work and never get crash , but now after the fx and use your plugin some time crash i don't know why , it's make like evry variable is nil but it's dosen't someone know that issue or i'm alone ?

ps : i'm french and dosen't use google tanslate so sorry if i make some error in my report

**Comment by joelwurtz** [comment]
should be good, reopen if it still crash
