### ISSUE TITLE
MySQL.ready issue only on linux (debian 9/mariadb)

### ISSUE THREAD

**Issue by MatPain** [brouznouf/fivem-mysql-async#25]
Hi,

thanks for your great ressource.

I have a trouble issue on Linux, débian 9 with mariadb.

On windows for my mysql test, i will load a server.lua with

```
MySQL.ready(function ()
	local countPlayer = MySQL.Sync.fetchScalar("SELECT COUNT(1) FROM users") -- get count from table in mysql 	
        local countPlayerText = 'YAHOU !! ligne en mysql = ' .. countPlayer -- friendly text 
	print(countPlayerText) -- print in console 
end)
```

so will work perfectly at the load server side, but on linux, nothing.

I m sure about my mysql connection because i tried to run my request directly and is fine.

Best Regards.

**Comment by MatPain** [comment]
On console at the start server 

```
Loaded MySqlConnector, Version=0.26.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1649366546
Loaded System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_16
49366546
Loaded System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_1649366546
YAHOU !! ligne en mysql = 1
```

on linux

`Loaded MySqlConnector, Version=0.26.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_2097110674`

stop at this line, no more

**Comment by bozoweed** [comment]
hi can you maybe try this ?
MySQL.ready(function ()
print("started mysql and ready")
	local countPlayer = MySQL.Sync.fetchScalar("SELECT COUNT(1) FROM users") -- get count from table in mysql 	
      if countPlayer ~= nill  then
print("get return")
if countPlayer > 0 then 
        local countPlayerText = 'YAHOU !! ligne en mysql = ' .. countPlayer -- friendly text 
	print(countPlayerText) -- print in console 
else
print("nothing found but get return")
end
else
print("no return from querry")
end
end)

**Comment by MatPain** [comment]
ah oui cool, vous êtes français ?

j'essaye votre modif et je reviens vers vous.

Pour info, j'avais écris un article sur l'installation de votre ressource : https://gta5.cool/comment-installer-fivem-mysql-async/

**Comment by bozoweed** [comment]
oui je le suis par contre je ne suis pas le créateur de la ressource, je suis juste le devellopeur de vision rp ^^

**Comment by MatPain** [comment]
ah mince je suis bête ^^

non j'ai absolument tout testé avec le mysql.ready, sur linux il ne s’exécute pas comme prévu.

Je suis évidemment bien certain que mon cache soit vide, que mon .lua se load et que ma requête mysql fonctionne correctement (exemple je place en direct et je restart ma ressource)

Le problème évidemment c'est que les ressources comme ES, ESX etc ne fonctionne pas également, sur windows je n'ai absolument aucun problème. J'ai essayé de réinstallé plusieurs fois le serveur, rien n'y fait.

Il y a des apt indispensable pour FiveM et mysql-sync sous Linux / Debian 9 ? 

merci pour ton aide en tous cas

**Comment by joelwurtz** [comment]
Try to start mysql async as the last resource

**Comment by MatPain** [comment]
exactly same ... 

do you know why i have a some diffenrece betwen windows and linux ?

i will reset my debian 9, what i need exactly ?

Mariadb or Mysql ? need anoher package ?

thanks you

**Comment by joelwurtz** [comment]
Don't know at all, the errors comes from fxs not mysql or other thing related

**Comment by MatPain** [comment]
i think too about data fivem :/ but i m only one with this problem on linux ? Oo

**Comment by joelwurtz** [comment]
No other person too with startup problem, read the forum post on fivem

**Comment by MatPain** [comment]
Hi,

i just upload your resource and now its right :) 

great developper.

if you want to help french people to install your plugin, you can add the link of my video in your wiki

https://www.youtube.com/watch?v=vDvbyqyzyQw
