### ISSUE TITLE
Rename Github repository name.

### ISSUE THREAD

**Issue by qlaffont** [brouznouf/fivem-mysql-async#27]
Hi, I have created [fvm-installer](https://github.com/qlaffont/fvm-installer) to install resources directly in FiveM folder. (Like Git)
So is it possible to rename your repository like this : _brouznouf/mysql-async_ ?
Thanks you do a good job and you help everyone ^^.

**Comment by joelwurtz** [comment]
Not possible to have a metadata file for each repository instead ?

**Comment by qlaffont** [comment]
Is not possible because i use Release API from Github. So the only way is
to rename your repo :/ to brouznouf/mysql-async
-- 

Best Regards

Quentin LAFFONT
8 lot parc du chateau
13190 ALLAUCH, FRANCE
+33 6 29 86 98 41

https://qlaffont.com <http://qlaffont.com/>
