### ISSUE TITLE
Simple SELECT

### ISSUE THREAD

**Issue by PichotM** [brouznouf/fivem-mysql-async#3]
Bonjour, j'ai une petite question à propos de l'instruction SELECT * matable, après la lib initiale qu'utilisait essentialmode cela retournait une table, telle que result[1], result[2] ... Mais il semblerai qu'avec async l'ordre soit exécuté plusieurs, fois. Comme vous pouvez le voir juste ici: 
https://image.prntscr.com/image/7fe6c73942c9411ea97fb639a716fd30.png

Merci à vous!

**Comment by bt0r** [comment]
Peux tu mettre ton script LUA en question ?

**Comment by PichotM** [comment]
MySQL.Async.fetchAll("SELECT * FROM entreprise", {}, function(result)

voici la commande utilisée

**Comment by PichotM** [comment]
je viens de voir ça :
local players = MySQL.Sync.fetchAll('SELECT id, name FROM player')
print(players[1].id)

ça pourrai m'aider ^^

**Comment by bt0r** [comment]
Le mieux étant de mettre tout ton code LUA pour bien voir ou ca pourrait clocher. 

Techniquement `MySQL.Async.fetchAll("SELECT * FROM entreprise", {}, function(result)` suivi de `local player = result[1]` devrait te renvoyer la même chose

**Comment by Meutledaron** [comment]
Up, toujours ce problème...

https://i.gyazo.com/ababe1ff41f6f8105c7cec1f362dc080.png

**Comment by enzio53** [comment]
SELECT * FROM tatabel WHERE collum = ? (remplace le ? par ta string)
