### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by SownEquation** [brouznouf/fivem-mysql-async#32]
When I try and launch the server I get this error.
`[ERROR] [MySQL] An critical error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `police` (`identifier` varchar(255) COLLATE utf8_unicode_ci NOT NULL,`dept` int(11) NOT NULL DEFAULT '0',`rank` int(11) NOT NULL DEFAULT '0') {=}": Method 'System.Security.Cryptography.X509Certificates.X509Certificate2..ctor' not found.   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0`

I've tried several different things and made sure all files are current. SSL for the user trying to connect is disabled. No idea what the x509Cert is? Any ideas?

**Comment by Syntasu** [comment]
Should be fixed in this PR: https://github.com/brouznouf/fivem-mysql-async/pull/36. @GHMatti
