### ISSUE TITLE
Script Crash and 6 minutes lag

### ISSUE THREAD

**Issue by manups4e** [brouznouf/fivem-mysql-async#35]
Sometimes, randomly the database crashes, it happens everytime with this long error, and everytime it starts with this line

[   4823750] [ERROR] [MySQL] An critical error happens on MySQL for query "SELECT * FROM users {=}": ServerSession is not connected.   at MySqlConnector.Core.ServerSession.VerifyConnected () [0x00052] in C:\Users\Matthias\Documents\GitHub\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:625

**Comment by GHMatti** [comment]
Try the node tree.

**Comment by manups4e** [comment]
you mean the newest update? beside the server cfg.. do i need to change something in my server / database to update?

**Comment by GHMatti** [comment]
not that i know of. it should work as usual after changing the connection string.
