### ISSUE TITLE
Access denied for user

### ISSUE THREAD

**Issue by weathergeek96** [brouznouf/fivem-mysql-async#42]
System: Ubuntu 16.04
MariaDB: 0.0.36-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04
MySQLAsync: 2.1.1.0
EssentialMode: 5.0.3

Error:
Started resource sessionmanager
Started resource mapmanager
Started resource chat
Started resource spawnmanager
Started gametype Freeroam
Started resource fivem
Started resource hardcap
Started resource rconlog
Started resource scoreboard
Started resource playernames
Loaded MySQLAsync.net, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1650378651
Instantiated instance of script MySQLAsync.MySQLThread.
Instantiated instance of script MySQLAsync.MySQLAsync.
Started resource mysql-async
Started resource async
EssentialMode is using MySQL!
Started resource essentialmode
Started resource esplugin_mysql
Started resource es_admin2
Started resource baseevents
Started resource es_extended
Started resource esx_menu_default
Started resource esx_menu_list
Started resource esx_menu_dialog
Authenticating server license key...
Server license key authentication succeeded. Welcome!
cfx> Sending heartbeat to live-internal.fivem.net:30110

Current version: 5.0.3
Updater version: 5.0.3

Everything is fine!

Started map fivem-map-skater
Started resource fivem-map-skater
Loaded MySqlConnector, Version=0.38.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92 into ScriptDomain_1650378651
Loaded Async!
hitch warning: frame time of 260 milliseconds
Loaded System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_1650378651
Loaded System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_1650378651
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM items {=}": Access denied for user 'fivem'@'localhost' (using password: YES)'

I have quadruple checked that the username and password are correct. The mysql console allows access via the username and password, and I can view the database from that user. I have been troubleshooting for days and haven't been able to figure out the issue.

**Comment by weathergeek96** [comment]
Turns out the issue was that I needed to type the mysql_connection_string instead of copy and paste. Weird as heck, but that's what fixed it.

**Comment by GHMatti** [comment]
Okay, make also sure you run one of the latest database versions. MariaDB 10.3.9 is current.
