### ISSUE TITLE
Server failing to start after upgrade to 3.0.1

### ISSUE THREAD

**Issue by SGTGunner** [brouznouf/fivem-mysql-async#43]
After upgrading mysql-async to 3.0.1 on a citizenfx build 785. I get the following errors:

```
c:\gl\builds\4ff63adb\0\cfx\fivem\vendor\node\src\connection_wrap.cc:81: Assertion (req_wrap) != (nullptr)' failed.

1: node::AddPromiseHook
 2: node::MakeCallback
 3: uv_write2
 4: uv_loop_init
 5: uv_run
 6: net::TcpServerManager::GetLoop
 7: net::TcpServerManager::GetLoop
 8: o_ceil
 9: BaseThreadInitThunk
10: RtlUserThreadStart

```

**Comment by GHMatti** [comment]
I ran 785 before and I am now on 792. How do I reproduce this?

**Comment by SGTGunner** [comment]
I got it working. I tried putting an IP address instead of `localhost` in the `set mysql_connection_string`.
I will close this issue. Thank you for the fast response.

**Comment by mifsopo** [comment]
@SGTGunner  just saying i know this is super fucking late reply but ive been search for this stuped but simple fucking answer for 3 days now, from downgrading artifacts to redoing sql database many MANY times.. and that was the answer i was looking for... if i could suck you off rn i would, i thank you my friend
