### ISSUE TITLE
Dates are broken

### ISSUE THREAD

**Issue by joelwurtz** [brouznouf/fivem-mysql-async#44]
Old versions of this script was returning date as a timestamp and now they are returned as a string, it may be nice to have an option keeping the old behavior

**Comment by GHMatti** [comment]
They were returned as DateTimes in C# which were serialized by MessagePack to unix timestamps for lua? I was not to sure about this behaviour as I never returned them and only used direct conversions.

But the JS MessagePack version seems to not encode Date, so I made it stringify.

Should be solvable pretty easily by manually replacing the Date columns with getTime(). Although this returns in ms not in seconds.

You think it is better to cut this off to int or float after dividing by 1000?

**Comment by joelwurtz** [comment]
It was returning a int (or long) only for type timestamp

AFAIK Date / DateTime types where converted into an object in C# which was keeped as an object in lua like this: `{'year': '2019, ...` but not sore about this

For milliseconds maybe you could return a double ? (like 15325ms would give 15.325 in lua ?)

**Comment by GHMatti** [comment]
Yeah that is probably a MySqlDateTime from the MySqlConnector.

I guess I'll add the conversion later today.
