### ISSUE TITLE
InvokeNatvie

### ISSUE THREAD

**Issue by mitchal01** [brouznouf/fivem-mysql-async#45]
So I have been getting in to fivem and the server I am on requested to use a "plugin" for he police clock in that also uses this "plugin" for a dependency. I keep getting the same error everytime I try to start my server. It would be very appreciated if you could help me in any way.

https://pastebin.com/7qvTSjmA

**Comment by mitchal01** [comment]
ok so I deleted my server files, restarted with a newer fivem resource and I have a hitch warning but so far no gibberish or errors.

**Comment by mitchal01** [comment]
Ok now I have an issue with the database not connecting correctly is there a certain collection I have to use ? I have this MySQL server running about 10 other things so I know they can all connect.

**Comment by mitchal01** [comment]
here I am being vague here is the error I receive.

[ERROR] [MySQL] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `police` (`identifier` varchar(255) COLLATE utf8_unicode_ci NOT NULL,`dept` int(11) NOT NULL DEFAULT '0',`rank` int(11) NOT NULL DEFAULT '0') {=}": Access denied for user 'root'@'%' to database 'fivem'

Which says trying to create table named police in database fivem, but doesn't have access to it. 


set mysql_connection_string "server=192.168.1.125;uid=root;password=**********;database=fivem"

**Comment by mitchal01** [comment]
![image](https://user-images.githubusercontent.com/25090451/46689740-65aa9f80-cbb5-11e8-9b3c-09b278bb7e3a.png)

**Comment by mitchal01** [comment]
This showing I have all  permissions or privileges

**Comment by mitchal01** [comment]
Ok I had to use mariadb instead of MySQL is there a reason for that ?

**Comment by mitchal01** [comment]
So as a formal notice, I had an error in my terminal, I upgraded to a newer version of fivem, I then switched database types from MySQL to MariaDB and now the issue is resolved.

**Comment by GHMatti** [comment]
I have no idea about MariaDB / MySQL. I never had any issues with both, apart from all the issues people are having with MySQL 8.
