### ISSUE TITLE
Close connection

### ISSUE THREAD

**Issue by benzon** [brouznouf/fivem-mysql-async#47]
I know this is a first world problem, but could you do a function that can be called on server shutdown/restart to close all current mysql connection, getting tirred of mysql log file now :P

**Comment by GHMatti** [comment]
I am currently trying to do some slight rewriting and broke it.  Guess I can add some command to restart the pool.

This is pretty easy.

**Comment by benzon** [comment]
My thought is more like, i got a command called serverretart, and it counts down and all that, when it kicks players from the server, then i could in the last line call something to close all mysql connections, so i avoid filling the error log lines, where it says connection package something cant recall the precise wording.

It's more a first world problem then anything else, but would be nice to be able to lose the connections down.

**Comment by GHMatti** [comment]
Won't implement a pool reset. Not needed anyways. If the connections dies by restarting a server properly or restarting the resource it servers the connections anyways.
