### ISSUE TITLE
Issue with utf8mb4

### ISSUE THREAD

**Issue by benzon** [brouznouf/fivem-mysql-async#48]
Got a player that it wont update.

ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x91\x8C

THE DB is running utf8mb4_danish_ci so it's abit wird it's not working can you look in to this? Old DLL version everything is fine only an issue with the new connecter.

**Comment by GHMatti** [comment]
I have got no idea about this one. I am using a general charset instead of a region bound one.

This is maybe a mysql.js issue.

**Comment by benzon** [comment]
New version is worse!

it wont load if they got a smiley in there name at all.

**Comment by benzon** [comment]
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE `users` SET `name` = 'BenZoN­ƒÿÇ' WHERE `identifier` = 'steam:*****'": ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x98\x80' for column 'name' at row 1

**Comment by GHMatti** [comment]
Give me the table structure like from heidisql.

**Comment by benzon** [comment]
CREATE DATABASE IF NOT EXISTS `drp_rebase` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

CREATE TABLE IF NOT EXISTS `users` (
  `identifier` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `license` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `money` int(11) DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `skin` longtext CHARACTER SET utf8mb4 DEFAULT NULL,
  `job` varchar(255) CHARACTER SET utf8mb4 DEFAULT 'unemployed',
  `job_grade` int(11) DEFAULT 0,
  `loadout` longtext CHARACTER SET utf8mb4 DEFAULT NULL,
  `position` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `bank` int(11) DEFAULT NULL,
  `permission_level` int(11) DEFAULT NULL,
  `group` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `firstname` varchar(50) CHARACTER SET utf8mb4 DEFAULT '',
  `lastname` varchar(50) CHARACTER SET utf8mb4 DEFAULT '',
  `dateofbirth` varchar(25) CHARACTER SET utf8mb4 DEFAULT '',
  `sex` varchar(15) CHARACTER SET utf8mb4 DEFAULT '',
  `height` varchar(5) CHARACTER SET utf8mb4 DEFAULT '',
  `isDead` bit(1) DEFAULT b'0',
  `status` longtext CHARACTER SET utf8mb4 DEFAULT NULL,
  `phone_number` int(11) DEFAULT NULL,
  `lastdigits` int(11) NOT NULL AUTO_INCREMENT,
  `last_property` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `tattoos` varchar(255) CHARACTER SET utf8mb4 DEFAULT '{}',
  `jail` int(11) DEFAULT 0,
  UNIQUE KEY `lastdigits` (`lastdigits`),
  KEY `identifier` (`identifier`)
) ENGINE=InnoDB AUTO_INCREMENT=1320 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

**Comment by benzon** [comment]
It might be the handshake it dos thats UTF8 is there an option to set default charset for the connection string ?

**Comment by GHMatti** [comment]
Indeed there is.

https://github.com/mysqljs/mysql#connection-options

see charset. You can set it with the mysql.js connection string i wanted to deprecate. Guess it stays.

```
mysql://usenrame:password@localhost/database?charset=UTF8_GENERAL_CI
```

**Comment by benzon** [comment]
Might be me thats an idiot now doing the connection string the wrong way.

**Comment by GHMatti** [comment]
https://regex101.com/r/B47UXQ/2

**Comment by benzon** [comment]
Ye it fixes it setting it to utf8mb_general_ci fixed the issue now it dos not throw a bitch flip on connection

**Comment by benzon** [comment]
So either the new connection string needs to stay, or the old method needs to have a charset option to, since it looks like it could be usefull for others to.

**Comment by JaroSound** [comment]
Im using "set mysql_connection_string "server=localhost;uid=mysqluser;password=password;database=fivem""

Any fix yet?

**Comment by GHMatti** [comment]
https://github.com/brouznouf/fivem-mysql-async/issues/48#issuecomment-435625201
https://github.com/brouznouf/fivem-mysql-async/issues/48#issuecomment-435626380

Reading would help. I currently need to take 2 weeks off, before I can push the charset option to the new connection string,

**Comment by benzon** [comment]
You need to use the new connection string to get it working:

set mysql://usenrame:password@localhost/database?charset=utf8mb4_general_ci&supportBigNumbers=true&multipleStatements=true

**Comment by schwim0341** [comment]
> You need to use the new connection string to get it working:
> 
> set mysql://usenrame:password@localhost/database?charset=utf8mb4_general_ci&supportBigNumbers=true&multipleStatements=true

Am I correct that style string does not work on a linux install?  I can't seem to make the move from the old style connect string.

**Comment by JaroSound** [comment]
set mysql://usenrame:password@localhost/database?charset=utf8mb4_general_ci&supportBigNumbers=true&multipleStatements=true

Is not workin for me, i still dont get the icons to work.

Version 2.1.2.0 work fine, i think i just use the old version...

**Comment by GHMatti** [comment]
```
set mysql_connection_string "mysql://usenrame:password@localhost/database?charset=utf8mb4_general_ci&supportBigNumbers=true&multipleStatements=true"
```

**Comment by MorgDev** [comment]
I'd like to add that the new connection string can also be used to specify character set:

set mysql_connection_string "server=localhost;uid=mysqluser;password=password;database=fivem;Character Set=utf8"

**Comment by GHMatti** [comment]
It is planned. in whatever way, I just need to write the regex.

It should be like 4-5 lines, but I am very busy at the moment.

**Comment by JaroSound** [comment]
> 
> 
> ```
> set mysql_connection_string "mysql://usenrame:password@localhost/database?charset=utf8mb4_general_ci&supportBigNumbers=true&multipleStatements=true"
> ```

This is not workin for me still dont get the icons to work "????????????"

**Comment by benzon** [comment]
The icons are a different story i gues the html document where you load icons need to have the UTF-8 Header i guess

**Comment by JaroSound** [comment]
But the icons works on 2.1.2.0. Icons like "👮|👨‍⚕️|👨‍🔧|🤵|🏠|🚚|🚕|🚗|🔫|🔗"

**Comment by GHMatti** [comment]
Works now with the new parsing of the configuration.
