### ISSUE TITLE
Might be a bug not sure

### ISSUE THREAD

**Issue by benzon** [brouznouf/fivem-mysql-async#49]
`RegisterServerEvent('esx_ambulancejob:firstSpawn')
AddEventHandler('esx_ambulancejob:firstSpawn', function()
	local _source    = source
	local identifier = GetPlayerIdentifiers(_source)[1]
	MySQL.Async.fetchScalar('SELECT isDead FROM users WHERE identifier = @identifier', {
		['@identifier'] = identifier
	}, function(isDead)
		if isDead == 1 then
			print(('esx_ambulancejob: %s attempted combat logging!'):format(identifier))
			TriggerClientEvent('esx_ambulancejob:requestDeath', _source)
		end
	end)
end)`

This is from esx_ambulancejob, the issue is isDead now returns a table insted of the being a single result, dont even think they noticed, but testet with 2 different versions of 3.x.x this was not a problem with 2.x.x

**Comment by benzon** [comment]
ah just did a for loop to fix it currently.

**Comment by GHMatti** [comment]
Already fixed in 3.0.8. See the closing reason.
