### ISSUE TITLE
mysql-async.js error on server

### ISSUE THREAD

**Issue by milo2491** [brouznouf/fivem-mysql-async#53]
mysql-async.js error on server boot

Error: (node:19044) UnhandledPromiseRejectionWarning: Error: No valid connection string found
    at parseConnectingString (mysql-async.js:5036:18)
    at global.on (mysql-async.js:5043:18)
    at citizen:/scripting/v8/main.js:193:28
Error: (node:19044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:19044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 

need help to fix error 
thank you 
milo

**Comment by GHMatti** [comment]
> Error: No valid connection string found

**Comment by milo2491** [comment]
i fix the error.
i was using this in the server config
set mysql_connection_string “addr=127.0.0.1;uid=username;database=essentialmode;pwd=password”

and i changed to this code and all worked
set mysql_connection_string “server=127.0.0.1;database=essentialmode;userid=username;password=password”

thanks for the help i fix it my self
