### ISSUE TITLE
WARNING: NON-EXISTENT NATIVE 000000004d52fe5b

### ISSUE THREAD

**Issue by manutrix** [brouznouf/fivem-mysql-async#54]
Salut, j'ai cette erreur `WARNING: NON-EXISTENT NATIVE 000000004d52fe5b` à cette ligne: [mysql-async.js#L4991](https://github.com/brouznouf/fivem-mysql-async/blob/master/mysql-async.js#L4991)

C'est une istallation "vanille". Le call vient de la ressource esplugin_mysql:

`MySQL.Async.fetchAll('SELECT * FROM users WHERE `identifier`=@identifier;', {identifier = identifier}, function(users)`

Je suis sur windows 10 Home 1809 64bit.

Est-ce que tu serais en mesure de m'orienter? Est-ce que c'est un problème de config? Pourtant il ajoute mon user donc il est capable de se connecter. Ça semble vraiment venir du `global.GetInvokingResource()`

Si t'as besoin de plus d'information!

Merci

Patrick

**Comment by GHMatti** [comment]
Update the server version.
