### ISSUE TITLE
Help with string please

### ISSUE THREAD

**Issue by bgn001** [brouznouf/fivem-mysql-async#55]
Hi I am trying to set string but for some reason it wont let me do it. 

![screenshot_1](https://user-images.githubusercontent.com/45293998/48952388-f0631600-ef39-11e8-968e-40caa2b4587c.png)

This is what im getting.

**Comment by Albin323** [comment]
try to use root with no password

**Comment by GHMatti** [comment]
Would you mind trying finding the actual query?

And the code in esx_vehicleshop
