### ISSUE TITLE
TriggerClientEvent in fetchAll callback

### ISSUE THREAD

**Issue by Identity-labs** [brouznouf/fivem-mysql-async#6]
TriggerClientEvent dont work in fetchAll callback ?

Server : 
`
AddEventHandler("item:getItems", function()
	print("item:getItems: " .. player)
	
  TriggerEvent('es:getPlayerFromId', source, function(user)
    local player = user.identifier
    MySQL.Sync.fetchAll(
      "SELECT IFNULL(ui.quantity, 0) quantity, i.id item_id, i.libelle, i.type "
      .. "FROM items i LEFT JOIN user_inventory ui ON ui.item_id = i.id AND user_id = @identifier", 
      { ['@identifier'] = player },
      function(result)
        print("resultcount: " .. tostring(#result))
      
        local items = {}
        if (result) then
          for _, v in ipairs(result) do
      		  local qty = 0
      		  if v.quantity ~= nil then
      			  qty = v.quantity
      		  end
      	
            t = { 
      			  ["quantity"] = tonumber(qty), 
      			  ["libelle"] = v.libelle,
      			  ["type"] = v.type 
      		  }
            table.insert(items, tonumber(v.item_id), t)
          end
        end
        TriggerClientEvent("item:getItems", source, items)
    end)
  end)
end)
`
Client : 
`
RegisterNetEvent("item:getItems")
AddEventHandler("item:getItems", function(THEITEMS)
    PrintChatMessage('item:getItems' .. tostring(#THEITEMS))
end)
`

**Comment by joelwurtz** [comment]
It should work with the last update to this library
