### ISSUE TITLE
MySQL.[A]sync.insert isn't documented

### ISSUE THREAD

**Issue by BrokenR3C0RD** [brouznouf/fivem-mysql-async#60]
Why wouldn't this be documented? Nothing on FiveM ever seems to be documented, even the official things. I don't get it ;(

**Comment by Jarrrk** [comment]
1. This isn't official
2. It's documented brilliantly

**Comment by GHMatti** [comment]
If I ever find time, I will work on the documentation. Currently it looks like, I can only support resources on weekends.
