### ISSUE TITLE
Error: Empty mysql_connection_string

### ISSUE THREAD

**Issue by mattish91** [brouznouf/fivem-mysql-async#66]
So basically i already have a mysql server running on my computer, this causes some issues durring startup since the port 3306 is already in use... i would like to know if i can change that by default? Also im getting this that might be related to the above?

> Error: (node:27864) UnhandledPromiseRejectionWarning: Error: Empty mysql_connection_string detected.
>     at global.on (mysql-async.js:5066:49)
>     at citizen:/scripting/v8/main.js:193:28
> Error: (node:27864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> Error: (node:27864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Not entirely sure what causes this since the error seams to be located at this line:

> if (connectionString === 'Empty') throw new Error('Empty mysql_connection_string detected.');

I have a clean install of mysql-async only.

**Comment by Cactusje** [comment]
Please tell how you fixed this
