### ISSUE TITLE
Error: (node:19) UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by AwakenDev** [brouznouf/fivem-mysql-async#72]
`Error: (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)`
&
`Error: (node:19) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout`

How to fix this?

**Comment by lowheartrate** [comment]
I am also getting this, someone?
```
Error: (node:11244) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at execute.then (mysql-async.js:5002:48)
Error: (node:11244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th promise which was not handled with .catch(). (rejection id: 1)
Error: (node:11244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promisenon-zero exit code.
```

**Comment by GHMatti** [comment]
Which version of MySQL are you using?

**Comment by AwakenDev** [comment]
I fixed it, my MySQL server disconnected the connection because of inactivity. I did put the timeout up and now it works.

**Comment by GHMatti** [comment]
Will add a timeout helper in 3.0.10.

**Comment by AwakenDev** [comment]
That would be nice. Think this issue can be closed now forever ;)
