### ISSUE TITLE
Error when players connect

### ISSUE THREAD

**Issue by Pelayori003** [brouznouf/fivem-mysql-async#74]
Error running system event handling function for resource esplugin_mysql: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/scheduler.lua:762: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:762: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:143: in field 'fetchAll'
        @esplugin_mysql/server.lua:5: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function citizen:/scripting/lua/scheduler.lua:218
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function citizen:/scripting/lua/scheduler.lua:182
Pelayori: sdsdsdsd
Sending heartbeat to live-internal.fivem.net:30110
Error resuming coroutine: @es_extended/server/functions.lua:122: attempt to index a nil value (global 'Async')
stack traceback:
        @es_extended/server/functions.lua:122: in field 'SavePlayers'
        @es_extended/server/functions.lua:133: in function 'saveData'

**Comment by GHMatti** [comment]
Delete your server's cache and try again.

**Comment by keketiger** [comment]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:890: No such export mysql_fetch_all in resource mysql-async

**Comment by SungJJinKang** [comment]
@keketiger i got this error too, is there anyone fixed this?

**Comment by SungJJinKang** [comment]
i solve this problem,
i don't know exact cause of this problem 

if you use fxserver creator, don't use it
just follow this doc ( https://docs.fivem.net/server-manual/setting-up-a-server/ )

**Comment by keketiger** [comment]
@SungJJinKang Personally I just reinstall fivem-mysql-async and the problem was solved.

**Comment by mar805cus** [comment]
i have same problem..
