### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by amakuu** [brouznouf/fivem-mysql-async#75]
I have a problem, i have this for about 3 months and i still dont found the solution.

[91mError: (node:21746) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at execute.then (mysql-async.js:5002:48)[0m
[91mError: (node:21746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)[0m

**Comment by GHMatti** [comment]
Update your mysql-async. This was fixed in the last patch.

**Comment by amakuu** [comment]
im sure i have update it

**Comment by amakuu** [comment]
do i need to clear cache or something?

**Comment by GHMatti** [comment]
Update with the version from sunday. mysql-async.js line 5002 is now a completely different one, you are not running on the newest version.
