### ISSUE TITLE
Mysql-async high tick

### ISSUE THREAD

**Issue by lvp11** [brouznouf/fivem-mysql-async#83]
Hey!

I'm getting this tick with mysql-async, that's too much, right?

![image](https://user-images.githubusercontent.com/47780889/59168078-a3781300-8b0a-11e9-94c3-bace7152881c.png)

Any ideas?

Thanks!

**Comment by GHMatti** [comment]
Does this happen with 3.0.8?

**Comment by GHMatti** [comment]
Fixed with 3.2.0 hopefully.
