### ISSUE TITLE
Buffer Shortage - Issue

### ISSUE THREAD

**Issue by DevMarshall95** [brouznouf/fivem-mysql-async#84]
https://i.gyazo.com/e0ccc23333a66635504a96a326c4b03f.png

Currently we're getting that error and we had to downgrade to version 2.1.1

Any ideas on what to do? We'd like to use the newest version if possible

**Comment by GHMatti** [comment]
Server version, and at best some short script to test against.

**Comment by Duqino** [comment]
I get the same error but it happens when i mess something up in the database. Like i have a lighter in the database for the shops script. Changing the name to lighter1 messes everything up. The server wont load anything.

**Comment by GHMatti** [comment]
Can you give me proper steps for the reproduction of this issue?

**Comment by Duqino** [comment]
1. In the DB table Items change name Ligter to Lighter1
2. Start the server. And i get the error

The item is for https://forum.fivem.net/t/new-update-release-esx-shops-with-bars-v-1-5-nightclubs/85625

also removing things makes the DB go crazy.
