### ISSUE TITLE
error load ui/app.js:14

### ISSUE THREAD

**Issue by Bobbbe** [brouznouf/fivem-mysql-async#85]
i have this in F8 console 
![screen1](https://user-images.githubusercontent.com/42454593/60480328-3530f700-9c57-11e9-9991-9286e411ae0d.png)
i don't see the error at line 14 !! you can help me please ?
i have the original file.

**Comment by qq9906898** [comment]
I have same problem too

**Comment by GHMatti** [comment]
Fixed in the latest version.

**Comment by qq9906898** [comment]
No fix, the 3.20 version still has this problem
![image](https://user-images.githubusercontent.com/49778649/61053902-ffdb9480-a420-11e9-859b-84cb19c2d88a.png)

**Comment by GHMatti** [comment]
does `mysql` in f8 console work, or does the entire vuejs app crash?

the backend and client works, just the question in how far this empty message affects the GUI for checking the performance of resources.

**Comment by SW1FT** [comment]
I also have this error and `mysql` does work for me.

**Comment by keketiger** [comment]
Hello, I also have the same problem, when I do F8. When we do the mysql command in F8 there are just empty graphics, here are some screenshots: 
![20190830164439_1](https://user-images.githubusercontent.com/34973659/64030048-1c08d180-cb46-11e9-8cd0-948e885d319a.jpg)
![20190830164442_1](https://user-images.githubusercontent.com/34973659/64030049-1c08d180-cb46-11e9-9cb4-d4350c2ee2f4.jpg)
![20190830164444_1](https://user-images.githubusercontent.com/34973659/64030050-1ca16800-cb46-11e9-875c-f0f8ce92a31a.jpg)
