### ISSUE TITLE
Database does not load

### ISSUE THREAD

**Issue by SpecialStos** [brouznouf/fivem-mysql-async#87]
Hey, 

out of the blue my old mysql-async  and i keep getting this errors: 
![image](https://user-images.githubusercontent.com/52541868/60861549-80cd3d00-a223-11e9-9413-4afb2a306acc.png). After trying many solutions i couldn't even find one. I tried using a backup of my resources in case i had made a mistake but still no luck. I tried another backup database that used to work but also no luck with that. Then i tried using your latest version but every time i use it i get stuck here with no errors, just this. 
![image](https://user-images.githubusercontent.com/52541868/60861639-c4c04200-a223-11e9-9a12-2c92846c6ac7.png) . Could you please help out why the server is not working out? I can't find a solution on this or explain to me why even the new resource wont load the database.

**Comment by GHMatti** [comment]
Update mysql-async, that issue was fixed some time ago.
