### ISSUE TITLE
Error I don't know what it is

### ISSUE THREAD

**Issue by DennisFusha** [brouznouf/fivem-mysql-async#92]
This is the error:

[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "UPDATE users SET job = 'police', job_grade = 2, loadout = '[]', position = '{\"x\":415.40000000002,\"y\":-988.0,\"z\":29.400000000002}' WHERE identifier = 'steam:11000011265965c'": ER_DATA_TOO_LONG: Data too long for column 'position' at row 1

Can you explain?

**Comment by schwim0341** [comment]
It's an es_extended error that has absolutely nothing to do with m-a.  Change the length of the position column in your users table from 32 to 255.

**Comment by DennisFusha** [comment]
> It's an es_extended error that has absolutely nothing to do with m-a. Change the length of the position column in your users table from 32 to 255.

Hey! So okay I know what you mean but could you help me out?

My discord is: Mr.BelgiumGamer#1378
please help xD

**Comment by schwim0341** [comment]
https://streamable.com/4vlg8

**Comment by DennisFusha** [comment]
> https://streamable.com/4vlg8

Thanks but I have MyAdmin haha I don't find the option to do that on there haha

**Comment by DennisFusha** [comment]
Found it nvm , thanks!
