### ISSUE TITLE
[ERROR] [MySQL] [esx_vehicleshop]

### ISSUE THREAD

**Issue by Taker54** [brouznouf/fivem-mysql-async#94]
![Sin título](https://user-images.githubusercontent.com/19560107/64701278-c8cd4200-d4a8-11e9-8e12-34c21a64fb71.png)

[ERROR] [MySQL] [esx_vehicleshop] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE owner = 'steam:11000013d2b376e' AND type = 'car' AND job = 'police'": ER_BAD_FIELD_ERROR: Unknown column 'type' in 'where clause'

I am new to this, someone who can help me, I receive this error when buying boats and at the police station.
The money is charged but nothing comes out

**Comment by Taker54** [comment]
How to fix pls

**Comment by Sylvesterb** [comment]
The column "type" is not known in your database. Not a issue of mysql-async. 
looks like you didnt load the SQL provided with your recource.

**Comment by Taker54** [comment]
But that's strange, including everything.

Do you have any contact so you can help me plis.

**Comment by Taker54** [comment]
Is there any way to put it manually?

**Comment by Taker54** [comment]
Buying cars does not give any problem

**Comment by Taker54** [comment]
And Other problem.
[ERROR] [MySQL] [esx_boat] An error happens on MySQL for query "UPDATE owned_vehicles SET `stored` = true WHERE `stored` = false AND type = 'boat'": ER_BAD_FIELD_ERROR: Unknown column 'stored' in 'where clause'

**Comment by josevloxx1** [comment]
[  script:mysql-async] [MariaDB:10.4.22-MariaDB] [ERROR] [es_extended] An error happens for query "INSERT INTO users

Anyone know how to fix it

**Comment by labrador936** [comment]
[ERROR] [MySQL] [esx_inventoryhud] An error happens on MySQL for query "UPDATE owned_vehicles SET owner =....
