### ISSUE TITLE
Slow query

### ISSUE THREAD

**Issue by deivismac** [brouznouf/fivem-mysql-async#95]
Ok so this wasnt an issue few months ago when i started the project. I tried debugging this issue for hours to see whats wrong. I disabled almost all resources. Updated to new versions. Nothing helped.

ISSUE
The query is taking too long to process i used a very simple query and it takes from 0.0005 sec to 5sec to process it, with no pattern, its just random.  I checked my cpu and ram usage and its fine only using like 10% of whats available. And the phpmyadmin returns the same query in miliseconds.

**Comment by GHMatti** [comment]
Do you have indexed your table properly?
