### ISSUE TITLE
ER_LOCK_DEADLOC

### ISSUE THREAD

**Issue by OPGamesTH** [brouznouf/fivem-mysql-async#96]
`[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "UPDATE user_inventory SET count = 10 WHERE identifier = 'steam:11000011705f1a4' AND item = 'water'": ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction`

how to fix this ? thank.

**Comment by opalao** [comment]
You did it?

**Comment by GHMatti** [comment]
Reproduction steps?
