### ISSUE TITLE
Error no such export mysql_fetch_all

### ISSUE THREAD

**Issue by IGHD** [brouznouf/fivem-mysql-async#99]
Error running system event handling function for resource esplugin_mysql: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/scheduler.lua:655: No such export mysql_fetch_all in resource mysql-async
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:655: in metamethod '__index'
        @mysql-async/lib/MySQL.lua:143: in field 'fetchAll'
        server.lua:15: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by harpreet9629** [comment]
I m getting same issue :(

**Comment by imvalient** [comment]
Make sure the name of this resource is mysql-async.

**Comment by Rman723** [comment]
The file has the correct name, and I am still getting this issue.

**Comment by GHMatti** [comment]
Add a dependency.
